print("what is Python?")
print()
print("A) A Large Snake")
print("B) A Programming language")
print("C) A sportcar")
print("D) A puppy")
print()
print("And now for some mathematics")
print("3 * (4-2) / 5 = ", (3*(4-2)/5))
print("2 ** 3 = ",(2**3))
